import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../server/app.mjs';
import { guidedPlan, planQuestion, validatePlan } from '../server/planner.mjs';
import { buildBriefing, evidenceSuggestions } from '../server/briefing.mjs';
const PASSWORD='Synthetic testing password 2026!';
async function setup(t,options={}){
  const app=createApp({databasePath:':memory:',production:false,authRateLimit:1000,identityRateLimit:1000,...options});const address=await app.listen(0,'127.0.0.1');const origin=`http://127.0.0.1:${address.port}`;
  t.after(()=>app.close());
  function client(){let cookie='',csrf='';return {async call(path,body,method=body===undefined?'GET':'POST',headers={}){const res=await fetch(origin+'/api'+path,{method,headers:{'Content-Type':'application/json',Origin:origin,Cookie:cookie,'X-CSRF-Token':csrf,...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});if(res.headers.get('set-cookie'))cookie=res.headers.get('set-cookie').split(';')[0];const data=await res.json();if(data.csrfToken)csrf=data.csrfToken;return {status:res.status,data,headers:res.headers};},async signup(tag){return this.call('/signup',{companyName:'Test '+tag,name:'Owner '+tag,email:tag+'@example.test',password:PASSWORD});}};}
  return {app,client,origin};
}
async function draft(c){const result=await c.call('/questions',{text:'Can we deliver Friday orders? What needs a decision?',context:'Orders B17 and B18',dueDate:'2026-10-02'});assert.equal(result.status,201);return result.data;}
async function launch(c,ownerId,assignment){let {question,requests}=await draft(c);let result=await c.call('/questions/'+question.id,{expectedVersion:question.version,context:question.context,dueDate:question.dueDate,requests:requests.map((r,i)=>({title:r.title,role:r.role,prompt:r.prompt,assigneeId:assignment?.[i] || ownerId}))},'PATCH');assert.equal(result.status,200);({question,requests}=result.data);result=await c.call(`/questions/${question.id}/launch`,{expectedVersion:question.version});assert.equal(result.status,200);return {question:result.data.question,requests};}
function responseInput(r,extra={}){return {expectedVersion:r.version,expectedResponseId:null,text:'Batch B17 is waiting for QA approval.',status:'blocked',source:'Synthetic QA log B17',observedAt:'2026-09-26T09:00:00Z',decisionNeeded:'Please confirm the authorized release owner.',...extra};}
async function invite(owner,c,email='member@example.test'){const result=await owner.call('/invites',{email});assert.equal(result.status,201);const joined=await c.call('/join',{token:result.data.invite.token,name:'Team member',password:PASSWORD});assert.equal(joined.status,201);return {user:joined.data.user,token:result.data.invite.token};}

test('signup, login, logout, cookies and passwords are independent of Workwork',async t=>{const {app,client}=await setup(t);const c=client();const r=await c.signup('auth');assert.equal(r.status,201);assert.match(r.headers.get('set-cookie'),/^quickview_session=.+HttpOnly; SameSite=Lax/);assert.match(app.store.userByEmail('auth@example.test').passwordHash,/^scrypt:/);assert.equal((await c.call('/state')).data.questions.length,0);await c.call('/logout',{});assert.equal((await c.call('/state')).status,401);assert.equal((await c.call('/login',{email:'auth@example.test',password:'incorrect-password'})).status,401);assert.equal((await c.call('/login',{email:'auth@example.test',password:PASSWORD})).status,200);});
test('invitations are one-use, replacement revokes earlier link, members cannot direct company',async t=>{const {client}=await setup(t);const owner=client(),member=client();await owner.signup('invite');const old=await owner.call('/invites',{email:'member@example.test'});const joined=await invite(owner,member);assert.equal((await client().call('/join',{token:old.data.invite.token,name:'Replay',password:PASSWORD})).status,400);assert.equal((await client().call('/join',{token:joined.token,name:'Replay',password:PASSWORD})).status,400);assert.equal((await member.call('/questions',{text:'Unauthorized'})).status,403);assert.equal((await member.call('/invites',{email:'other@example.test'})).status,403);});
test('draft plans are private to managers and do not create assignments until launched',async t=>{const {client}=await setup(t);const owner=client(),member=client();const id=(await owner.signup('draft')).data.user.id;await invite(owner,member);const d=await draft(owner);assert.equal(d.requests.length,4);assert.ok(d.requests.every(r=>r.assigneeId===null));assert.equal((await member.call('/state')).data.requests.length,0);assert.equal((await member.call(`/requests/${d.requests[0].id}/responses`,responseInput(d.requests[0]))).status,404);assert.equal((await owner.call(`/questions/${d.question.id}/launch`,{expectedVersion:1})).status,400);const l=await launch(owner,id);assert.equal((await member.call('/state')).data.questions.length,1);assert.equal(l.question.status,'live');});
test('complete assigned response, follow-up, history, decision and close/reopen workflow',async t=>{const {client}=await setup(t);const owner=client(),member=client();const ownerId=(await owner.signup('workflow')).data.user.id;const {user}=await invite(owner,member);const {question,requests}=await launch(owner,ownerId,[user.id]);const r=requests[0];const submitted=await member.call(`/requests/${r.id}/responses`,responseInput(r));assert.equal(submitted.status,201);let state=(await owner.call('/state')).data;assert.equal(state.briefings[0].answered,1);assert.equal(state.briefings[0].attention.length,1);assert.equal(state.briefings[0].unknown.length,3);
const follow=await owner.call(`/requests/${r.id}`,{expectedVersion:1,assigneeId:user.id,followup:'Has QA approved B17? Cite the approval.'},'PATCH');assert.equal(follow.status,200);state=(await owner.call('/state')).data;assert.equal(state.briefings[0].answered,0);assert.equal(state.briefings[0].rows[0].state,'update_requested');assert.equal(state.responses.length,1);
const updated=await member.call(`/requests/${r.id}/responses`,responseInput(follow.data.request,{expectedResponseId:submitted.data.response.id,text:'QA approval is not yet confirmed.',status:'unknown',decisionNeeded:''}));assert.equal(updated.status,201);state=(await owner.call('/state')).data;assert.equal(state.responses.length,2);assert.equal(state.briefings[0].answered,1);assert.equal(state.briefings[0].unknown.length,4);assert.equal(state.briefings[0].rows[0].response.text,'QA approval is not yet confirmed.');assert.equal((await owner.call(`/questions/${question.id}/decisions`,{text:'Do not release the batch without QA confirmation.'})).status,201);
const closed=await owner.call(`/questions/${question.id}/close`,{expectedVersion:question.version});assert.equal(closed.status,200);assert.equal((await member.call(`/requests/${r.id}/responses`,responseInput(follow.data.request))).status,409);assert.equal((await owner.call(`/questions/${question.id}/reopen`,{expectedVersion:closed.data.question.version})).status,200);});
test('tenant isolation rejects foreign question, assignee, response and reusable evidence',async t=>{const {client}=await setup(t);const a=client(),b=client();const aid=(await a.signup('tenant-a')).data.user.id,bid=(await b.signup('tenant-b')).data.user.id;const qa=await launch(a,aid),qb=await launch(b,bid);const ra=qa.requests[0],rb=qb.requests[0];const ans=(await a.call(`/requests/${ra.id}/responses`,responseInput(ra))).data.response;const state=(await b.call('/state')).data;assert.equal(state.responses.length,0);assert.ok(state.members.every(m=>m.id!==aid));assert.equal((await b.call(`/requests/${ra.id}/responses`,responseInput(ra))).status,404);assert.equal((await b.call(`/questions/${qa.question.id}/close`,{expectedVersion:qa.question.version})).status,404);assert.equal((await b.call(`/requests/${rb.id}`,{expectedVersion:rb.version,assigneeId:aid,followup:'Foreign member'},'PATCH')).status,404);assert.equal((await b.call(`/requests/${rb.id}/responses`,responseInput(rb,{reuseResponseId:ans.id}))).status,404);assert.equal((await b.call(`/requests/${rb.id}/responses`,responseInput(rb,{authorId:aid}))).status,400);});
test('unassigned member cannot answer, follow up, close or record decisions',async t=>{const {client}=await setup(t);const owner=client(),member=client();const id=(await owner.signup('authorization')).data.user.id;await invite(owner,member);const {question,requests}=await launch(owner,id);const r=requests[0];assert.equal((await member.call(`/requests/${r.id}/responses`,responseInput(r))).status,403);assert.equal((await member.call(`/requests/${r.id}`,{expectedVersion:1,assigneeId:id,followup:'No'},'PATCH')).status,403);assert.equal((await member.call(`/questions/${question.id}/close`,{expectedVersion:question.version})).status,403);assert.equal((await member.call(`/questions/${question.id}/decisions`,{text:'No'})).status,403);});
test('stale plans, duplicate answers and out-of-date follow-ups are rejected',async t=>{const {client}=await setup(t);const c=client();const id=(await c.signup('versions')).data.user.id;const {question,requests}=await launch(c,id);const r=requests[0];assert.equal((await c.call(`/questions/${question.id}/close`,{expectedVersion:1})).status,409);const body=responseInput(r);assert.equal((await c.call(`/requests/${r.id}/responses`,body)).status,201);assert.equal((await c.call(`/requests/${r.id}/responses`,body)).status,409);assert.equal((await c.call(`/requests/${r.id}`,{expectedVersion:1,assigneeId:id,followup:'New update'},'PATCH')).status,200);assert.equal((await c.call(`/requests/${r.id}/responses`,body)).status,409);});
test('source reuse preserves provenance without changing the original evidence',async t=>{const {client}=await setup(t);const c=client();const id=(await c.signup('reuse')).data.user.id;const {requests}=await launch(c,id);const a=(await c.call(`/requests/${requests[0].id}/responses`,responseInput(requests[0]))).data.response;const copy=await c.call(`/requests/${requests[1].id}/responses`,responseInput(requests[1],{text:'This is an updated interpretation.',reuseResponseId:a.id}));assert.equal(copy.status,201);assert.equal(copy.data.response.reused.text,a.text);const state=(await c.call('/state')).data;assert.equal(state.responses[0].text,a.text);});
test('CSRF, foreign origin, invalid payloads and dates fail closed',async t=>{const {client}=await setup(t);const c=client();await c.signup('guards');assert.equal((await c.call('/questions',{text:'test'},'POST',{'X-CSRF-Token':''})).status,403);assert.equal((await c.call('/questions',{text:'test'},'POST',{Origin:'https://other.test'})).status,403);assert.equal((await c.call('/questions',{text:'test'},'POST',{'Sec-Fetch-Site':'cross-site'})).status,403);assert.equal((await c.call('/questions',{text:'test',dueDate:'2026-02-30'})).status,400);assert.equal((await c.call('/questions',{text:'test',companyId:'forged'})).status,400);assert.equal((await c.call('/questions',{text:'x'.repeat(70000)})).status,413);});
test('question drafting is bounded per company',async t=>{const {client}=await setup(t,{companyWriteLimit:1});const c=client();await c.signup('quota');assert.equal((await c.call('/questions',{text:'How is production?'})).status,201);assert.equal((await c.call('/questions',{text:'What is next?'})).status,429);});
test('accounts, sessions and question plans survive database reopen',async t=>{const dir=await mkdtemp(join(tmpdir(),'quickview-persist-'));t.after(()=>rm(dir,{recursive:true,force:true}));const databasePath=join(dir,'test.sqlite');const app=createApp({databasePath,production:false});const addr=await app.listen(0,'127.0.0.1');const url=`http://127.0.0.1:${addr.port}`;const signed=await fetch(url+'/api/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyName:'Persistent',name:'Owner',email:'persistent@example.test',password:PASSWORD})});const cookie=signed.headers.get('set-cookie').split(';')[0],session=await signed.json();const q=await fetch(url+'/api/questions',{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie,'X-CSRF-Token':session.csrfToken},body:JSON.stringify({text:'What is ready?'})});assert.equal(q.status,201);await app.close();const app2=createApp({databasePath,production:false});t.after(()=>app2.close());const addr2=await app2.listen(0,'127.0.0.1');const loaded=await fetch(`http://127.0.0.1:${addr2.port}/api/state`,{headers:{Cookie:cookie}});assert.equal(loaded.status,200);assert.equal((await loaded.json()).questions[0].text,'What is ready?');});
test('guided plans support manufacturing domains and Korean without inventing measurements',()=>{for(const q of ['Can we deliver on Friday?','금요일 납품은 가능한가요?','How is the new line readiness?','Why are quality defects increasing?','How are our costs changing?','What happened?']){const p=guidedPlan(q);assert.ok(p.requests.length>=3);assert.equal(p.engine,'guided');assert.doesNotThrow(()=>validatePlan({requests:p.requests}));}assert.match(guidedPlan('금요일 납품은 가능한가요?').requests[0].prompt,/[가-힣]/);});
test('optional AI drafting validates output and falls back on provider failures',async()=>{const env={QUICKVIEW_AI_MODE:'openai',OPENAI_API_KEY:'synthetic-key',OPENAI_MODEL:'test-model'};let sent;const requests=[{title:'Scope',role:'Operations',prompt:'What facts are known?'}];const result=await planQuestion('What is ready?','Synthetic context',{env,fetchImpl:async(url,opts)=>{sent=JSON.parse(opts.body);return {ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({requests})}]}]})};}});assert.equal(result.engine,'openai');assert.equal(sent.store,false);assert.equal(sent.text.format.strict,true);assert.equal((await planQuestion('What is ready?','',{env,fetchImpl:async()=>{throw new Error('offline');}})).engine,'guided');assert.throws(()=>validatePlan({requests:[{...requests[0],assigneeId:'invented'}]}));assert.throws(()=>validatePlan({requests:[]}));});
test('briefings count current responses, retain unknowns and never compute business KPI from answer coverage',()=>{const q={id:'q',status:'live'},requests=[{id:'r',questionId:'q',version:2}],old=[{id:'a',requestId:'r',requestVersion:1,status:'on_track',text:'Earlier report'}];let b=buildBriefing(q,requests,old);assert.equal(b.answered,0);assert.equal(b.rows[0].response.text,'Earlier report');b=buildBriefing(q,requests,[...old,{id:'b',requestId:'r',requestVersion:2,status:'unknown',text:'No verified outcome'}]);assert.equal(b.answered,1);assert.equal(b.unknown.length,1);assert.match(b.headline,/unknown/);assert.equal(b.kpi,undefined);});
test('suggestions are bounded candidates and exclude the same request',()=>{const r={id:'r1',title:'Production batch bearing',prompt:'Check bearing delivery'},rs=[r,{id:'r2'}],answers=[{id:'a',requestId:'r1',text:'Production bearing batch'},{id:'b',requestId:'r2',text:'The bearing delivery is delayed',createdAt:'2026-09-26T00:00:00Z'}];assert.deepEqual(evidenceSuggestions(r,answers,rs).map(s=>s.responseId),['b']);});
test('production requires HTTPS origin and returns secure independent cookies',async t=>{assert.throws(()=>createApp({databasePath:':memory:',production:true,appOrigin:''}),/APP_ORIGIN/);assert.throws(()=>createApp({databasePath:':memory:',production:true,appOrigin:'http://example.test'}),/HTTPS/);const {client}=await setup(t,{production:true,appOrigin:'https://quickview.example.test'});const c=client();const r=await c.call('/signup',{companyName:'Secure test',name:'Owner',email:'secure@example.test',password:PASSWORD},'POST',{Origin:'https://quickview.example.test'});assert.equal(r.status,201);assert.match(r.headers.get('set-cookie'),/; Secure/);assert.match(r.headers.get('strict-transport-security'),/31536000/);});
test('evidence suggestions use the last submitted response even with equal timestamps',()=>{const r={id:'r1',title:'Production bearing delivery',prompt:'Check bearing delivery'},rs=[r,{id:'r2'}];const answers=[{id:'old',requestId:'r2',text:'Bearing delivery delayed',createdAt:'same'},{id:'new',requestId:'r2',text:'Bearing delivery confirmed',createdAt:'same'}];assert.deepEqual(evidenceSuggestions(r,answers,rs).map(s=>s.responseId),['new']);});
